# code to install packages in the docker file
install.packages("dplyr")
install.packages("lubridate")
install.packages("readr")
install.packages("magrittr")
install.packages("plotly")
install.packages("openssl")
install.packages("rvest")
install.packages("qdap")
install.packages("stringr")
install.packages("scales")
install.packages("reshape2")
install.packages("gapminder")
install.packages("plumber")
install.packages("lazytrade")
